name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions: write-all


jobs:
  publish_on_mac:
    name: 'Publish on Mac'
    runs-on: macos-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Set up Node.js 🔨
        uses: actions/setup-node@v3.7.0
        with:
          cache: 'yarn'

      - name: Install dependencies ⚙️
        run: yarn run install

      - name: Build 🍞 
        run: yarn run build

      - name: Publish 📦
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run publish

        
